global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['nodejs-app:3000']
        
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    metrics_path: /scrape
    params:
      target: [redis://redis:6379]